### PR TITLE
barista(builder): Fixes an issue with the index file generation.

### LINKED ISSUE #905: Barista: Server Side rendering of index page fails.
# Bug Report

Currently, all barista pages are static pages that are rendered on the server. Due to a race condition, the index.html file gets replaced with its original file in the builder. That is the reason why the index page is not server side rendered.

All other pages are fine.

## Possible solution.

Rename the output file to `index.original.html` and launch it for the generation. (This is already done)
* Fix the bug with the renaming.

### PR DESCRIPTION
**Pull request by lukasholzer**
Fixes #905

Fixes a problem where the index file was not generated propperly and therefore the server crashed on the healthcheck.

Added further tests to test the file renaming and rendering.

### <strong>Pull Request</strong>

<hr>
Hi, thank you for contributing to Barista with this pull request (PR).

To ensure a fast process and merging of your PR please make sure it fulfills the
coding standards and contribution guidelines.

- A feature proposal has been provided, discussed and approved first.
- There is a meaningful description of the issue in GitHub (Screenshots are
  often helpful).
- If the PR introduces breaking-changes or deprecations it matches the following
  guidelines.
  - The commit message follows our commit guidelines.
  - Tests for the changes have been added (for bug fixes / features).
  - Docs have been added / updated (for bug fixes / features).

Please choose the type appropriate for the changes below: <br>

#### Checklist

- [ ] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by lukasholzer** [comment]
@rowa-audil FYI

File: libs/workspace/src/test-setup.ts [hunk 1]
```diff
@@ -13,3 +13,13 @@
...
+
+jest.mock('fs', () => {
+  const actualFs = jest.requireActual('fs');
+  const unionfs = require('unionfs').default;
+  unionfs.reset = () => {
+    // fss is unionfs' list of overlays
+    unionfs.fss = [actualFs];
+  };
+  return unionfs.use(actualFs);
+});
```
Comment (ffriedl89) [inline libs/workspace/src/test-setup.ts:25]: Can you please explain why we need unionfs here? :)

File: package.json [hunk 2]
```diff
@@ -144,6 +144,7 @@
     "dotenv": "^8.2.0",
     "express": "^4.15.2",
     "extract-loader": "^5.0.1",
+    "fsevents": "^2.1.3",
```
Comment (ffriedl89) [inline package.json:147]: why is this added? Is it a peer dep of unionfs?

File: libs/workspace/src/test-setup.ts (hunk 1 above)
Comment (lukasholzer) [reply libs/workspace/src/test-setup.ts:25]: As stated in the specs - we merge the memes with the actual fs with unionfs so you can still imoprt and read files from your fs but it overlays the memfs. It tries all file operations first on the memfs and if it does not succeed it callbacks to the normal fs is required we cannot use only memfs as the builders need the actual fs to gather files etc.

image


This enables the usage of adding a memfs on top of the normal fs

```typescript
  const vol = Volume.fromJSON(
    {
      'index.original.html': 'original',
    },
    '/test-root',
  );

  // Merge the current fs with the mocked volume
  const fsMock: any = fs;
  fsMock.use(vol);
```

and we can get all the changes that are performed since this call on the fs.

File: package.json (hunk 2 above)
Comment (lukasholzer) [reply package.json:147]: nope is a relict of a further try will remove it :)

Had it before unionfs to mock the fs but unionfs is way easier to handle
