### PR TITLE
fix(chart): Fixes an issue where series visibility was not retained over new data set.

### LINKED ISSUE #1412: Chart filtering resets when new data arrives.
# Bug Report

## Expected Behavior

Column filtering shouldn't be affected by new data.

## Current Behavior

After data changes all columns are visible again.

## Steps to Reproduce
- https://stackblitz.com/edit/github-vilm5e?file=src/chart/chart-stream-example/chart-stream-example.html

### Used Versions:

- **typescript**: 3.8.3
- **@angular/cdk**: 9.2.4
- **@dynatrace/barista-components**: 7.6.0

## Attachments

barista_visability_reseting

### PR DESCRIPTION
**Pull request by tomheller**
### <strong>Pull Request</strong>

When new seriesdata was set into the chart, the visibility settings for each series were not carried
over, as the chart is completely destroyed and reinstantiated every time new data is set.
To mitigate this issue, whenever a new data is set, we now look in the old series dataset for a
series with the same name and carry over the `visible` setting from the previous source.

Fixes #1412

#### Type of PR

Bugfix

#### Checklist

- [x] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: libs/barista-components/chart/src/chart.ts [hunk 1]
```diff
@@ -231,11 +231,19 @@ export class DtChart
...
       });
     } else {
-      this._currentSeries = series;
+      if (series) {
+        this._currentSeries = series.map(
+          retainSeriesVisibility(this._chartObject?.series),
+        );
+      } else {
+        this._currentSeries = series;
+      }
```
Comment (lukasholzer) [inline libs/barista-components/chart/src/chart.ts:246]: NIT: This would reduce duplication and can eliminate an unnecessary variable declaration.
I thought we have the `prefer-conditional-expression` lint rule in place for that... 🤔

```suggestion
      this._currentSeries = !series
          ? series
          : series.map(retainSeriesVisibility(this._chartObject?.series));
```
