### PR TITLE
fix(quick-filter): Use internal uid for the filter generation.

### LINKED ISSUE #1522: [quick-filter]: async options are not properly handled (group vanishes, leading to follow-up issues)
# Bug Report

## Expected Behavior

No exception

## Current Behavior

```
[TypeError] e.startsWith is not a function
     at DtQuickFilterGroup (=> startsWith) (node_modules/@dynatrace/barista-components/fesm5/dynatrace-barista-components-experimental-quick-filter.js:1571:29)
     at DtQuickFilterGroup (=> findIndex) (node_modules/@dynatrace/barista-components/fesm5/dynatrace-barista-components-experimental-quick-filter.js:1566:49)
     at Object.updateDirectives (node_modules/@dynatrace/barista-components/experimental/quick-filter/dynatrace-barista-components-experimental-quick-filter.d.ts.ɵa.html:14:54)
     at updateRenderer (=> updateDirectives) (node_modules/@angular/core/fesm5/core.js:31802:72)
     at checkAndUpdateView (=> updateDirectives) (node_modules/@angular/core/fesm5/core.js:31455:14)
     at callViewAction (=> checkAndUpdateView) (node_modules/@angular/core/fesm5/core.js:31696:21)
     at execEmbeddedViewsAction (=> callViewAction) (node_modules/@angular/core/fesm5/core.js:31659:17)
     at checkAndUpdateView (=> execEmbeddedViewsAction) (node_modules/@angular/core/fesm5/core.js:31456:5)
     at callViewAction (=> checkAndUpdateView) (node_modules/@angular/core/fesm5/core.js:31696:21)
```

## Steps to Reproduce

1. select an async autocomplete item, where the `showInSidebar` predicate is false

### Used Versions:

- **@dynatrace/barista-components**: 7.5.1

## Detailed Description

looks like the exception happens when calling `_isNothingSelected`
see also https://dev-jira.dynatrace.org/browse/APM-254006

### LINKED ISSUE #1647: [quick-filter] use internal id path from filter field and not require it in the data source

### PR DESCRIPTION
**Pull request by lukasholzer**
This issue should be a further step to make the quick filter stable.

Fixes #1647
Fixes #1522

### <strong>Pull Request</strong>

<hr>
Hi, thank you for contributing to Barista with this pull request (PR).

To ensure a fast process and merging of your PR please make sure it fulfills the
coding standards and contribution guidelines.

- A feature proposal has been provided, discussed and approved first.
- There is a meaningful description of the issue in GitHub (Screenshots are
  often helpful).
- If the PR introduces breaking-changes or deprecations it matches the following
  guidelines.
  - The commit message follows our commit guidelines.
  - Tests for the changes have been added (for bug fixes / features).
  - Docs have been added / updated (for bug fixes / features).

Please choose the type appropriate for the changes below: <br>

#### Checklist

- [ ] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: libs/barista-components/experimental/quick-filter/src/quick-filter-group.ts [hunk 1]
```diff
@@ -51,7 +52,7 @@ import {
     class: 'dt-quick-filter-group',
   },
 })
-export class DtQuickFilterGroup {
+export class DtQuickFilterGroup<T = any> {
```
Comment (thomaspink) [inline libs/barista-components/experimental/quick-filter/src/quick-filter-group.ts:55]: NIT: I think I would go for `unkown` here.

**Review by thomaspink — DISMISSED** [review]

**Review by peter-affenzeller — APPROVED** [review]

**Review by thomaspink — APPROVED** [review]

**Review by bardosmisi — APPROVED** [review]
