### PR TITLE
Overlay: Fix mousemove

### LINKED ISSUE #220: DtOverlay: when triggering the overlay near the screen border it appears with a wrong width
# Bug Report

## Expected Behavior

Overlay should appears with the width of the content
## Current Behavior

Overlay appears with a wrong width when triggering the overlay near the screen border 

## Steps to Reproduce

1. Go to verlay-demo.component.scss
2. Add the following style
```
span {
  display: flex;
  width: 100%;
}
```
3. Hover the overlay near the border
image

1. 

### Used Versions:

- **node**: 12.1.0 
- **npm**:  6.9.0 
- **typescript**: 3.5.3
- **angular**: 8.2.14
- **@angular/cdk**: 8.2.3 
- **@dynatrace/barista-components**:  4.15.0

### LINKED ISSUE #772: Overlay is misplaced for trigger element consisting of mutiple elements
As discussed with Lukas:

See example:
https://github-slwyzc.stackblitz.io

When you hover over the first element everything is fine, hovering over "=" or the last word you see that the overlay is misplaced.

### PR DESCRIPTION
**Pull request by ffriedl89**
This PR fixes some long standing issues that keep popping up.

Fixes #772
Fixes #220

The discussion on what to do with the overlay is already quite long. This is the intermediate step of fixing what we have right now the best way I could. 

Plan for the future: Provide default config that can be used with the cdk overlay service and directives. 
And create a "tooltip" (working title) component that would cover 95% percent of the use cases in the template. More will follow in the #86

### CODE REVIEW

**Comment by ffriedl89** [comment]
FYI @deeleman

File: libs/barista-components/overlay/src/overlay-trigger.ts [hunk 1]
```diff
@@ -93,16 +89,13 @@ export class DtOverlayTrigger<T> extends _DtOverlayTriggerMixin
     private _ngZone: NgZone,
     private _focusMonitor: FocusMonitor,
     @Attribute('tabindex') tabIndex: string,
+    // @ts-ignore
```
Comment (lukasholzer) [inline libs/barista-components/overlay/src/overlay-trigger.ts]: May you explain why typescript failed here on this line?

Or can we remove that?

File: libs/barista-components/overlay/src/overlay.ts [hunk 2]
```diff
@@ -93,11 +92,16 @@ const DT_OVERLAY_POSITIONS: ConnectedPosition[] = [
  */
 export const DT_OVERLAY_NO_POINTER_CLASS = 'dt-no-pointer';
 
+// TODO: Deprecate this once we have a tooltip component in place
```
Comment (lukasholzer) [inline libs/barista-components/overlay/src/overlay.ts]: Have you created a follow-up issue for this?

File: libs/barista-components/overlay/src/overlay.ts [hunk 3]
```diff
@@ -107,10 +111,14 @@ export class DtOverlay implements OnDestroy {
...
     private _injector: Injector,
     private _overlay: Overlay,
+    // @ts-ignore unused variable
     private _viewportRuler: ViewportRuler,
     // tslint:disable-next-line:no-any
+    // @ts-ignore unused variable
     @Inject(DOCUMENT) private _document: any,
+    // @ts-ignore unused variable
     private _platform: Platform,
+    // @ts-ignore unused variable
```
Comment (lukasholzer) [inline libs/barista-components/overlay/src/overlay.ts]: If they are unused can we deprecate them?

File: libs/barista-components/overlay/src/overlay-trigger.ts (hunk 1 above)
Comment (ffriedl89) [reply libs/barista-components/overlay/src/overlay-trigger.ts]: Oh good catch - this was a mistake! 👍

File: libs/barista-components/overlay/src/overlay.ts (hunk 2 above)
Comment (ffriedl89) [reply libs/barista-components/overlay/src/overlay.ts]: We already have #86  - i'll add more information in the next days there.

File: libs/barista-components/overlay/src/overlay.ts (hunk 3 above)
Comment (ffriedl89) [reply libs/barista-components/overlay/src/overlay.ts]: Plan is to deprecated the entire component. That's why I didn't add a deprecation notice per argument.

File: libs/barista-components/overlay/src/overlay-trigger.ts (hunk 1 above)
Comment (ffriedl89) [reply libs/barista-components/overlay/src/overlay-trigger.ts]: Or not :D it is also unused. :D also did not check the file I am in while reading the comment. 

So it is unused since we don't need the platform anymore.
