### PR TITLE
barista(filter-field): Add partial option.

### LINKED ISSUE #868: Filter field: Second async call lets category disappear
# Bug Report

## Expected Behavior

When the data is loaded async a second time the category should stay selected and only the autocomplete/suggestion values should change.

## Current Behavior

The category vanishes and the filter field shows the new suggestions on the top level.

## Steps to Reproduce

https://stackblitz.com/edit/github-9bfdsj

or

Use Barista example code for "Loading options asynchronously" and replace the following:

`currentFilterChanged(
    event: DtFilterFieldCurrentFilterChangeEvent<any>,
  ): void {
    if (event.added[0] === this.DATA.autocomplete[0]) {
      // Emulate a http request
      setTimeout(() => {
        this._dataSource.data = this.ASYNC_DATA;
      }, 1000);
       // Emulate a second http request
      setTimeout(() => {
        this._dataSource.data = this.ASYNC_DATA;
      }, 3000);
    }
  }`

## Context (Environment)

We show a dashboard list which can be filtered for several categories. The owners list can get really long on big systems to we wanted to implement a server side filtering for it and load the suggestions async while typing. We did this by using a debounce time of 400ms. So the user started typing a few letters and gets suggestions as soon as he stops. This works fine but if he continues writing afterwards, a second async call will be made and this makes the 'Owner' category disappear.

[APM-230713_Async_Owner_Suggestions_Issue.zip](https://github.com/dynatrace-oss/barista/files/4474231/APM-230713_Async_Owner_Suggestions_Issue.zip)

### PR DESCRIPTION
**Pull request by christian-fischer**
Fixes #868

### <strong>Pull Request</strong>

<hr>
Hi, thank you for contributing to Barista with this pull request (PR).

To ensure a fast process and merging of your PR please make sure it fulfills the
coding standards and contribution guidelines.

- A feature proposal has been provided, discussed and approved first.
- There is a meaningful description of the issue in GitHub (Screenshots are
  often helpful).
- If the PR introduces breaking-changes or deprecations it matches the following
  guidelines.
  - The commit message follows our commit guidelines.
  - Tests for the changes have been added (for bug fixes / features).
  - Docs have been added / updated (for bug fixes / features).

Please choose the type appropriate for the changes below: <br>

#### Type of PR

Feature (non-breaking change which adds functionality)

#### Checklist

- [x] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by christian-fischer** [comment]
Thanks for your feedback @tomheller 
Yes, I'd like to take you up on your offer to provide some guidance as the test spec for the filter-field is indeed a bit overwhelming for me.

**Comment by christian-fischer** [comment]
Update: added test case for partial updates in collaboration with @tomheller

**Comment by christian-fischer** [comment]
update: rebased to current upstream master, fixed merge conflicts

File: libs/barista-components/filter-field/src/types.ts [hunk 1]
```diff
@@ -156,10 +157,11 @@ export function dtAutocompleteDef<D = unknown, OG = unknown, Op = unknown>(
   optionsOrGroups: DtNodeDef<OG>[],
   distinct: boolean,
   async: boolean,
+  partial: boolean,
```
Comment (ffriedl89) [inline libs/barista-components/filter-field/src/types.ts:160]:
```suggestion
  partial: boolean = false,
```
We need to set a default value and by doing so make this optional, otherwise this would introduce a breaking change.

File: libs/barista-components/filter-field/src/types.ts [hunk 2]
```diff
@@ -45,6 +45,7 @@ export interface DtNodeDef<D = unknown> {
 export interface DtAutocompleteDef<OpGr = unknown, Op = unknown> {
   distinct: boolean;
   async: boolean;
+  partial: boolean;
```
Comment (ffriedl89) [inline libs/barista-components/filter-field/src/types.ts:48]: this needs to be optional as well :) 
```suggestion
  partial?: boolean;
```

Comment (christian-fischer) [reply libs/barista-components/filter-field/src/types.ts]: 👍

**Comment by christian-fischer** [comment]
update: rebase to current upstream master & implemented changes regarding semantic versioning as proposed by @ffriedl89

**Comment by ffriedl89** [comment]
Master only due to types taken from breaking change for 7.0.0

**Comment by andular** [comment]
@christian-fischer and @tomheller thanks for the fix! we can now consider to remove our workaround again and use this partial async loading feature instead. :)
