### PR TITLE
chore(chart): Fixed an configuration issue with the min/max example.

### LINKED ISSUE #409: Barista: Error in min/max chart example
# Bug Report

## Current Behavior

When hovering over the line in the min/max chart example, the following console error is displayed: "Uncaught TypeError: Cannot read property 'lineWidth' of undefined..."

## Steps to Reproduce

Can be reproduced in Barista and the demos app.

### PR DESCRIPTION
**Pull request by tomheller**
Fixed an issue where the lineWidth was set in the wrong options set
which resulted in a highcharts error.

Fixes #409

### <strong>Pull Request</strong>

<hr>
Hi, thank you for contributing to Barista with this pull request (PR).

To ensure a fast process and merging of your PR please make sure it fulfills the
coding standards and contribution guidelines.

- A feature proposal has been provided, discussed and approved first.
- There is a meaningful description of the issue in GitHub (Screenshots are
  often helpful).
- If the PR introduces breaking-changes or deprecations it matches the following
  guidelines.
  - The commit message follows our commit guidelines.
  - Tests for the changes have been added (for bug fixes / features).
  - Docs have been added / updated (for bug fixes / features).

Please choose the type appropriate for the changes below: <br>

#### Checklist

- [x] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: libs/examples/src/chart/chart-min-max-example/chart-min-max-example.ts [hunk 1]
```diff
@@ -70,11 +64,19 @@ export class DtExampleChartMinMax {
...
+    } as Highcharts.IndividualSeriesOptions,
     {
       name: 'Line 1',
       type: 'line',
       data: this._minMaxChartLineSeries,
     },
   ];
+  constructor() {
+    console.log(this.series);
+  }
```
Comment (ffriedl89) [inline libs/examples/src/chart/chart-min-max-example/chart-min-max-example.ts]: Remove please :)
