### PR TITLE
fix(chart): Fixes an issue with the overlay of the selection area not updating.

### LINKED ISSUE #608: Chart selection: timeframe in the overlay is not updated
# Bug Report

## Expected Behavior

After setting the chart selection programatically, the timeframe in the selection overlay should be updated accordingly.

## Current Behavior

If having an existing selection and setting the selection programatically through the `value` property, the timeframe in the selection overlay still has the old value.

The value gets updated after hovering the chart.

## Steps to Reproduce

1. Select any range in the chart (i.e. by hand)
2. Set the selection programatically to some other value

You can paste the following snippets to the `chart-demo.component`.

```html
<button (click)="setTimeframe()">set timeframe</button>
```
```typescript
setTimeframe(): void {
  this.lastTimeframe = [
    this.lastTimeframe[0] - 100_000,
    this.lastTimeframe[1] + 100_000,
   ];
   this.dtChartRange.value = this.lastTimeframe;
}
```

## Context (Environment)

We have to add the selection based on some filters after loading data. This should override a selection done by previously by the user.

### Used Versions:

- **node**: 12.4.0
- **npm**: 6.13.7
- **typescript**: 3.4.3
- **angular**: 8.0.0
- **@angular/cdk**: 8.0.0
- **@dynatrace/barista-components**: 5.2.0

## Attachments

selection-overlay-not-updated

### PR DESCRIPTION
**Pull request by tomheller**
### <strong>Pull Request</strong>

Fixes #608

#### Type of PR
Bugfix

#### Checklist

- [x] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: components/chart/src/selection-area/selection-area.ts [hunk 1]
```diff
@@ -828,6 +830,7 @@ export class DtChartSelectionArea implements AfterContentInit, OnDestroy {
               ref,
               viewPortOffset,
             );
+            this._changeDetectorRef.markForCheck();
```
Comment (lukasholzer) [inline components/chart/src/selection-area/selection-area.ts]: please move this to the end of the `_updateOrCreateOverlay` function.

File: apps/components-e2e/src/components/chart/selection-area/selection-area.e2e.ts [hunk 2]
```diff
@@ -141,6 +142,17 @@ test('should increase the selection by dragging the left handle', async (testCon
     .match(/Jul 31 \d{2}:15 — \d{2}:23/g);
 });
 
+test('should create a range and update the overlay when updating the range value programmatically', async (testController: TestController) => {
+  await createRange(520, { x: 310, y: 100 }, testController);
```
Comment (lukasholzer) [inline apps/components-e2e/src/components/chart/selection-area/selection-area.e2e.ts]: You can chain this as well:

```
await createRange(520, { x: 310, y: 100 }, testController)
    .expect(overlayText.textContent)
    .match(/Jul 31 \d{2}:17 — \d{2}:23/g)
```
