### PR TITLE
fix(event-chart): Round time labels in x-axis

### LINKED ISSUE #614: Event chart x-axis formatting
# Bug Report

## Expected Behavior

X-axis formatting should not contain too many decimals

## Current Behavior

Currently x-axis may contain up to 9 or 10 decimals and overlaps with the next tick

## Possible Solution

Round the result to a given amount of decimals

### Used Versions:

- **node**: 12.0.0
- **npm**: 6.9.0
- **typescript**: 3.5.3
- **angular**: 8.2.14
- **@angular/cdk**: 8.2.3
- **@dynatrace/barista-components**: 5.1.1

## Attachments
image

### PR DESCRIPTION
**Pull request by subarroca**
Closes #614

#### Type of PR

Bugfix (non-breaking change which fixes an issue)

#### Checklist

- [x] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [x] Lint and unit tests pass locally with my changes
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: components/event-chart/src/event-chart.ts [hunk 1]
```diff
@@ -813,15 +813,20 @@ function formatRelativeTimestamp(timestamp: number): string {
...
-    return `${timestamp / sec}s`;
+    return `${roundUp(timestamp / sec, decimals)} s`;
   }
   return `${timestamp}ms`;
   // tslint:enable: no-magic-numbers
 }
+
+function roundUp(num: number, decimals: number): number {
+  return Math.round(10 ** decimals * num) / 10 ** decimals;
+}
```
Comment (ffriedl89) [inline components/event-chart/src/event-chart.ts]: TIL:  ** is the exponentiation operator. 
Could you please add a jsdoc comment to the function to explain what it does :) 
It would also be amazing if you could add some unit tests for that function.

**Comment by tomheller** [comment]
Hi @subarroca!
Thank you for that fix, this seems pretty straight forward. 
It seems like you have not signed the CLA yet. Everybody that contributes to the library needs to sign our Contributors License Agreement.

The `roundUp` function looks great. I know that it feels a little bit unnecessary, but would be able to add some unit tests for that function as well?

File: components/event-chart/src/event-chart.ts (hunk 1 above)
Comment (subarroca) [reply components/event-chart/src/event-chart.ts]: ok, I'll add those

File: components/event-chart/src/event-chart.spec.ts [hunk 2]
```diff
@@ -632,6 +632,39 @@ describe('DtEventChart', () => {
...
+      it('should return seconds', () => {
+        expect(formatRelativeTimestamp(10_000)).toBe('10 s');
+      });
+
+      it('should return minutes', () => {
+        expect(formatRelativeTimestamp(600_000)).toBe('10 min');
+      });
+
+      it('should return hours', () => {
+        expect(formatRelativeTimestamp(2 * 60 * 60_000)).toBe('2 h');
```
Comment (ffriedl89) [inline components/event-chart/src/event-chart.spec.ts]: `60_000` so much love for this 🎉

**Comment by tomheller** [comment]
Cherry picked the commits to 5.x. and 5.2.x
