### PR TITLE
barista: Add/fix theming of categories.

### LINKED ISSUE #157: Barista: Page theme
The pages in Barista need a page theme (a different color for each of the sections - brand, ressources, patterns, components, tools)

### PR DESCRIPTION
**Pull request by lara-aigmueller**
### <strong>Pull Request</strong>

fixes #157 

<hr>
Hi, thank you for contributing to Barista with this pull request (PR).

To ensure a fast process and merging of your PR please make sure it fulfills the
coding standards and contribution guidelines.

- A feature proposal has been provided, discussed and approved first.
- There is a meaningful description of the issue in GitHub (Screenshots are
  often helpful).
- If the PR introduces breaking-changes or deprecations it matches the following
  guidelines.
  - The commit message follows our commit guidelines.
  - Tests for the changes have been added (for bug fixes / features).
  - Docs have been added / updated (for bug fixes / features).

Please choose the type appropriate for the changes below: <br>

#### Checklist

- [ ] I have read the CONTRIBUTING doc and I follow the PR guidelines
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

File: apps/barista/src/app.ts [hunk 1]
```diff
@@ -21,6 +21,14 @@ import { BaLocationService } from './shared/location.service';
 import { BaPageService } from './shared/page.service';
 import { map } from 'rxjs/operators';
 
+const PAGE_THEME_MAP = new Map<string, string>([
+  ['brand', 'purple'],
+  ['resources', 'blue'],
+  ['components', 'royalblue'],
+  ['patterns', 'turquoise'],
+  ['tools', 'yellow'],
```
Comment (ffriedl89) [inline apps/barista/src/app.ts]: We can remove tools :) No need for tools in the new version anymore

File: apps/barista/src/app.ts [hunk 2]
```diff
@@ -63,6 +71,18 @@ export class BaApp {
     map((path: { title: string; href: string }[]) => path.length > 1),
   );
 
+  /** @internal Gets the page theme based on the current location. */
+  _pageTheme$ = this.locationService.currentPath$.pipe(
+    map((path: string) => {
+      let pageTheme = 'turquoise';
```
Comment (ffriedl89) [inline apps/barista/src/app.ts]: Can we make the default more prominent in a `const DEFAULT_PAGE_THEME` variable

File: apps/barista/src/layout/smalltile/smalltile.scss [hunk 3]
```diff
@@ -1,46 +1,26 @@
 @import '../../styles/global/variables';
 @import '../../../../../components/core/src/style/colors';
```
Comment (ffriedl89) [inline apps/barista/src/layout/smalltile/smalltile.scss]: We can use the preprocessed styles
```suggestion
@import 'colors';
```

File: apps/barista/src/layout/smalltile/smalltile.ts [hunk 4]
```diff
@@ -35,7 +34,7 @@ export class BaSmallTile {
     if (this.data) {
       switch (this.data.category) {
         case 'Brand':
-          return 'green';
+          return 'purple';
         case 'Resources':
           return 'blue';
         case 'Components':
```
Comment (ffriedl89) [inline apps/barista/src/layout/smalltile/smalltile.ts]: Can we remove the case 'Tools' below?

File: apps/barista/src/layout/tile/tile.scss [hunk 5]
```diff
@@ -134,26 +136,26 @@ $gridgap: 20px;
...
   @include tile-theme($royalblue-500, $royalblue-500, $royalblue-700);
 }
 
-.ba-theme-green {
+.dt-theme-green :host {
   @include tile-theme($green-500, $green-500, $green-700);
 }
 
-.ba-theme-yellow {
+.dt-theme-yellow :host {
```
Comment (ffriedl89) [inline apps/barista/src/layout/tile/tile.scss]: i guess this can be removed

File: apps/barista/src/styles/global/_theme.scss [hunk 6]
```diff
@@ -0,0 +1,41 @@
...
+  --ba-pagetheme-light: #{$purple-400};
+}
+
+.dt-theme-royalblue {
+  --ba-pagetheme: #{$royalblue-500};
+  --ba-pagetheme-dark: #{$royalblue-700};
+  --ba-pagetheme-light: #{$royalblue-400};
+}
+
+.dt-theme-yellow {
```
Comment (ffriedl89) [inline apps/barista/src/styles/global/_theme.scss]: I guess we can remove this :)
