### PR TITLE
barista/Element losing focus bug fix

### LINKED ISSUE #878: Find as you type feature in icon search steals focus of text input control
Search works but input into field is interrupted by background reload. 

Steps to reproduce:
Use chrome Version 80.0.3987.163 (Official Build) (64-bit) on Windows 10
Go to /resources/icons on the internal barista version
Type search term, allow to reload while typing
-> focus from input box is lost

### PR DESCRIPTION
**Pull request by rowa-audil**
An element's focus was lost due to router navigation when changing the query.
Fixed by manually navigating.
Done by @tomheller.

Fixes #878

### CODE REVIEW

File: apps/barista-design-system/src/pages/single-page/components/icon-overview-content/icon-overview-content.ts [hunk 1]
```diff
@@ -87,12 +91,23 @@ export class BaIconOverviewContent implements OnInit, AfterViewInit, OnDestroy {
...
-        this._router.navigate([], {
-          queryParams,
-          relativeTo: this._activatedRoute,
-        });
+        if (value.length) {
+          // we need to push the query change state without calling the angulars
+          // router navigate, because navigating would trigger the angular-routers
+          // scrollPositionRestoration, which will remove the focus from the current
+          // element and scroll back to top.
+          window.history.pushState(
```
Comment (lukasholzer) [inline apps/barista-design-system/src/pages/single-page/components/icon-overview-content/icon-overview-content.ts:99]: Please add a platform check because this will fail in universal

File: apps/barista-design-system/src/pages/single-page/components/icon-overview-content/icon-overview-content.ts [hunk 2]
```diff
@@ -87,12 +92,31 @@ export class BaIconOverviewContent implements OnInit, AfterViewInit, OnDestroy {
...
+        if (this._platform.isBrowser) {
+          if (value.length) {
+            // we need to push the query change state without calling the angulars
+            // router navigate, because navigating would trigger the angular-routers
+            // scrollPositionRestoration, which will remove the focus from the current
+            // element and scroll back to top.
+            window.history.pushState(
+              {},
+              '',
+              `${window.location.origin}${window.location.pathname}`,
```
Comment (ffriedl89) [inline apps/barista-design-system/src/pages/single-page/components/icon-overview-content/icon-overview-content.ts:104]: I guess the value should be added as a parameter in the case its not empty - so it would need to be inverted. 

```suggestion
              `${window.location.origin}${window.location.pathname}?iconFilter=${value}`,
```

File: apps/barista-design-system/src/pages/single-page/components/icon-overview-content/icon-overview-content.ts [hunk 3]
```diff
@@ -87,12 +92,31 @@ export class BaIconOverviewContent implements OnInit, AfterViewInit, OnDestroy {
...
+            );
+          } else {
+            window.history.pushState(
+              {},
+              '',
+              `${window.location.origin}${window.location.pathname}?iconFilter=${value}`,
```
Comment (ffriedl89) [inline apps/barista-design-system/src/pages/single-page/components/icon-overview-content/icon-overview-content.ts:110]:
```suggestion
              `${window.location.origin}${window.location.pathname}`,
```

**Comment by tomheller** [comment]
As this is partially my code, I wanted to remove myself from the reviewers, but github wont let me. Please do not wait or recognize my review.

**Comment by rowa-audil** [comment]
@lukasholzer 
Could you have a look at the CI issue I'm having because the build step fails due to a socket hang up.

**Comment by lukasholzer** [comment]
> @lukasholzer
> Could you have a look at the CI issue I'm having because the build step fails due to a socket hang up?

@rowa-audil  in this case you can retrigger the step from failed:
image

Can happen if something timed out.

**Comment by rowa-audil** [comment]
@lukasholzer 
I tried that a couple of times to no avail.

**Comment by lukasholzer** [comment]
> @lukasholzer
> I tried that a couple of times to no avail.

Have you tried to run it locally and checked if it fails? Because maybe your code changes produce an error and that's why it fails – on the master the build is passing so it has to be your code.

**Comment by rowa-audil** [comment]
Currently, trying to tackle the CI issue. @ffriedl89

**Comment by lukasholzer** [comment]
@rowa-audil  please rebase with the current master to fix the failing build.
