### PR TITLE
fix(option): Fixes multiple selected bug when using keyboard and mouse

### LINKED ISSUE #1070: [Filter field] First entry always seems to be selected.
# Bug Report

## Expected Behavior

Only the entry where the mouse hovers over should be colored.

## Current Behavior

The entry where the mouse hovers and the first entry are colored

## Possible Solution

Should be fixed, since the user may be confused what he will select when clicking.

## Steps to Reproduce

Just try the first filter field here:
https://barista.dynatrace.com/components/filter-field
* also check autocomplete, select, and combobox

1. Go to https://barista.dynatrace.com/components/filter-field
2. Click on the first filter field
3. Hover over the third entry. You will see that the first entry is also colored as if "selected"

## Context (Environment)
Found on:
Firefox Version: 76.0.1
Chrome Version: 83.0.4103.61

### Used Versions:

- **node**: >=10.13.0
- **yarn**: >=1.13.0 <2
- **typescript**: 3.8.3
- **angular**: 9.1.0
- **@angular/cdk**: 9.2.0
- **@dynatrace/barista-components**: 6.5.2

## Attachments
filter-field-bug

### PR DESCRIPTION
**Pull request by rowa-audil**
@ffriedl89 @thomaspink 

Tom and I have come up with this sollution for the filter field selection "bug" we have.
The DtOption has a subject containing the item that is hovered on mousemove which the autocomplete subscribes to setting the active item.

Any thoughts?

Fixes #1070

### CODE REVIEW

File: libs/barista-components/core/src/option/option.ts [hunk 1]
```diff
@@ -62,6 +62,7 @@ export class DtOptionSelectionChange<T> {
     '[class.dt-option-disabled]': 'disabled',
     '(click)': '_handleClick($event)',
     '(keydown)': '_handleKeydown($event)',
+    '(mousemove)': '_handleMouseMove()',
```
Comment (thomaspink) [inline libs/barista-components/core/src/option/option.ts:65]: Attaching a `mousemove` this way will trigger a CD on every move. Please use `zone.runOutsideAngular` and attach the event handler in that callback (maybe via `fromEvent`). Note, When the correct event has been captured and you emit the hovered output you need to wrap the emitting again in a `zone.run`

File: libs/barista-components/autocomplete/src/autocomplete.ts [hunk 2]
```diff
@@ -220,6 +226,19 @@ export class DtAutocomplete<T>
 
   ngAfterViewInit(): void {
     this._portal = new TemplatePortal(this._template, this._viewContainerRef);
+    this._options.changes
+      .pipe(
+        // startWith(null),
```
Comment (tomheller) [inline libs/barista-components/autocomplete/src/autocomplete.ts:231]: Remove commented code.
```suggestion
```

File: libs/barista-components/experimental/combobox/src/combobox.spec.ts [hunk 3]
```diff
@@ -116,10 +116,10 @@ describe('Combobox', () => {
     fixture.detectChanges();
     focusInput(input);
 
-    expect(trigger.classList.contains('dt-combobox-open')).toBeTruthy();
     expect(
       overlayContainerElement.querySelectorAll('dt-option').length,
     ).toEqual(3);
+    expect(trigger.classList.contains('dt-combobox-open')).toBeTruthy();
```
Comment (tomheller) [inline libs/barista-components/experimental/combobox/src/combobox.spec.ts:122]: I don't think this change is necessary.

File: libs/barista-components/experimental/combobox/src/combobox.ts [hunk 4]
```diff
@@ -337,6 +337,7 @@ export class DtCombobox<T> extends _DtComboboxMixinBase
       this._templatePortalContent,
       this._viewContainerRef,
     );
+
```
Comment (tomheller) [inline libs/barista-components/experimental/combobox/src/combobox.ts:340]: I don't think this change is necessary. 
```suggestion
```

File: libs/barista-components/select/src/select.ts [hunk 5]
```diff
@@ -524,10 +524,18 @@ export class DtSelect<T> extends _DtSelectMixinBase
...
+          merge(...this.options.map((option) => option._optionHovered)),
+        ),
+        takeUntil(this._destroy),
+      )
+      .subscribe((a) => {
+        this._ngZone.run(() => {
+          this._keyManager.setActiveItem(a);
+        });
         this._resetOptions();
-        this._initializeSelection();
```
Comment (tomheller) [inline libs/barista-components/select/src/select.ts:530]: Why do we remove the initializeSelection here. I guess this should still be the behaviour to set the first item active.

**Comment by tomheller** [comment]
Some e2e tests would be very nice, otherwise this looks fairly good.

File: libs/barista-components/autocomplete/src/autocomplete.ts [hunk 6]
```diff
@@ -220,6 +226,18 @@ export class DtAutocomplete<T>
 
   ngAfterViewInit(): void {
     this._portal = new TemplatePortal(this._template, this._viewContainerRef);
+    this._options.changes
+      .pipe(
+        takeUntil(this._destroy$),
```
Comment (lukasholzer) [inline libs/barista-components/autocomplete/src/autocomplete.ts:231]: The `takeUntil` has to be the last operator – when you perform a `switchMap` you switch your stream to a new source and the new source does not get completed with the takeUntil. 
In your code the `takeUntil` only handles the `option.changes` subscription that is triggered by the `switchMap`.

In your case I would go with a simple store the result as subscription and unsubscribe no need for an extra subject.

File: libs/barista-components/select/src/select.ts [hunk 7]
```diff
@@ -942,11 +957,13 @@ export class DtSelect<T> extends _DtSelectMixinBase
   }
 
   private _resetOptions(): void {
+    console.log('');
```
Comment (lukasholzer) [inline libs/barista-components/select/src/select.ts:960]:
```suggestion
```

File: libs/barista-components/select/src/select.ts [hunk 8]
```diff
@@ -942,11 +957,13 @@ export class DtSelect<T> extends _DtSelectMixinBase
...
     const changedOrDestroyed = merge(this.options.changes, this._destroy);
 
     this.optionSelectionChanges
       .pipe(takeUntil(changedOrDestroyed))
       .subscribe((event) => {
+        console.log(event.isUserInput);
```
Comment (lukasholzer) [inline libs/barista-components/select/src/select.ts:966]:
```suggestion
```

File: libs/barista-components/core/src/option/option.ts [hunk 9]
```diff
@@ -225,13 +240,24 @@ export class DtOption<T> implements Highlightable, AfterViewChecked, OnDestroy {
...
+  }
+
   /**
    * @internal
    * Selects the option while indicating the selection came from the user. Used to
    * determine if the select's view -> model callback should be invoked.
    */
   _selectViaInteraction(): void {
     if (!this.disabled) {
+      // debugger;
```
Comment (lukasholzer) [inline libs/barista-components/core/src/option/option.ts:260]:
```suggestion
```

File: libs/barista-components/core/src/option/option.ts [hunk 10]
```diff
@@ -142,10 +148,19 @@ export class DtOption<T> implements Highlightable, AfterViewChecked, OnDestroy {
         this._stateChanges.next();
       }
     }
+    this._ngZone.runOutsideAngular(() => {
+      fromEvent(this._element.nativeElement, 'mousemove')
```
Comment (ffriedl89) [inline libs/barista-components/core/src/option/option.ts:152]: could we use mouseover instead? We only want to know when somebody enters the option and not all consecutive move events as well.

File: libs/barista-components/core/src/option/option.ts [hunk 11]
```diff
@@ -125,6 +130,7 @@ export class DtOption<T> implements Highlightable, AfterViewChecked, OnDestroy {
   constructor(
     private _element: ElementRef,
     private _changeDetectorRef: ChangeDetectorRef,
+    private _ngZone: NgZone,
```
Comment (ffriedl89) [inline libs/barista-components/core/src/option/option.ts:133]: Same here regarding the breaking change.

File: libs/barista-components/autocomplete/src/autocomplete.ts [hunk 12]
```diff
@@ -208,10 +210,14 @@ export class DtAutocomplete<T>
...
     Subscription.EMPTY;
 
+  /** Subject used for unsubscribing */
+  private _destroy$ = new Subject<void>();
+
   constructor(
     private _changeDetectorRef: ChangeDetectorRef,
     private _elementRef: ElementRef<HTMLElement>,
     private _viewContainerRef: ViewContainerRef,
+    private _ngZone: NgZone,
```
Comment (ffriedl89) [inline libs/barista-components/autocomplete/src/autocomplete.ts:220]: @lukasholzer isn't this considered a breaking change? 
How should we handle this - we can't really go without the zone here - so there is no way around not having this functionality and no zone. One option would be to make the zone optional and not have the functionality when no zone is given. And make it mandatory in the next major version. - Should we add this to the breaking changes for 8? 
What do you think?

Comment (lukasholzer) [reply libs/barista-components/autocomplete/src/autocomplete.ts:220]: Yea as it comes from the DI it would be ok only if you would extend from the autocomplete then it would break so we have to make it optional and mark it as deprecated to be non optional with version 9 I would say when we release 8 these days. 

I'm really not sure about how we should handle this (Can we mark the component class itself as internal?) so using it via DI is ok but if you want to extend it is on your own risk?

Because to be honest I don't want to support extending from the component.

File: libs/barista-components/core/src/option/option.ts (hunk 10 above)
Comment (lukasholzer) [reply libs/barista-components/core/src/option/option.ts:152]: mousemove with takeuntil destroy is really long –> you would listen the whole component lifecycle for mousemoves.

**Comment by rowa-audil** [comment]
I rebased the master into the branch in order for the e2e test to run through. Otherwise it would throw an error because the deprecated empty-state class doesn't have a decorator

File: libs/barista-components/select/src/select.ts [hunk 13]
```diff
@@ -526,8 +526,24 @@ export class DtSelect<T> extends _DtSelectMixinBase
...
+      .pipe(
+        startWith(null),
+        switchMap(() =>
+          merge(...this.options.map((option) => option._optionHovered)),
+        ),
+        takeUntil(this._destroy),
+      )
+      .subscribe((option) => {
+        this._ngZone.run(() => {
+          console.log('set');
```
Comment (lukasholzer) [inline libs/barista-components/select/src/select.ts:544]: please cleanup
```suggestion
```

File: libs/barista-components/core/src/option/option.ts [hunk 14]
```diff
@@ -225,6 +246,17 @@ export class DtOption<T> implements Highlightable, AfterViewChecked, OnDestroy {
     this._selectViaInteraction();
   }
 
+  /** Contains the hovered option as a stream */
+  _optionHovered = new Subject<DtOption<T>>();
+
+  /** @internal Handles mousemove on the option and selects the not active option */
+  _handleMouseOver(): void {
+    if (!this.active) {
+      console.log('setting');
```
Comment (lukasholzer) [inline libs/barista-components/core/src/option/option.ts:255]: cleanup

```suggestion
```

**Review by lukasholzer — APPROVED** [review]

**Review by heartdisease — APPROVED** [review]

**Review by thomaspink — APPROVED** [review]
